In [23]:
# Step 1: Import the relevant python libraries for the analysis
import pandas as pd
from pandas import DataFrame
import numpy as np
import matplotlib.pyplot as plt
import sklearn
%matplotlib inline

In [26]:
# Step 2: Load and test dataset and set the index if applicable
materna = pd.read_csv('mortalidad_materna.csv')
materna.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18163 entries, 0 to 18162
Data columns (total 58 columns):
Año de nacimiento                                   18163 non-null int64
Mes de nacimiento                                   18163 non-null int64
Descripción del mes de nacimiento                   18163 non-null object
Día de nacimiento                                   18163 non-null int64
Genero                                              18163 non-null int64
Clave de la edad                                    18163 non-null object
Edad cumplida                                       18163 non-null int64
Estado conyugal                                     18163 non-null int64
Descripción del estado conyugal                     18163 non-null object
Entidad de residencia                               18163 non-null int64
Descripción de entidad de residencia                18163 non-null object
Municipio de residencia                             18163 non-null int64
Descripción del municipio de residencia             18163 non-null object
Localidad de residencia                             18163 non-null int64
Descripción de la localidad de residencia           18163 non-null object
Tamaño de localidad                                 18163 non-null int64
Descripción del tamaño de localidad                 18163 non-null object
Ocupación habitual                                  18163 non-null int64
Descripción de la ocupación habitual                17762 non-null object
Escolaridad                                         18163 non-null int64
Descripción de la escolaridad                       18163 non-null object
Derechohabiencia                                    18163 non-null int64
Descripción de la derechohabiencia                  18163 non-null object
Entidad de ocurrencia                               18163 non-null int64
Descripción de la entidad de ocurrencia             18163 non-null object
Municipio de ocurrencia                             18163 non-null int64
Descripción del municipio de ocurrencia             18163 non-null object
Localidad de ocurrencia                             18163 non-null int64
Descrición de la localidad de ocurrencia            18163 non-null object
Sitio donde ocurrio la defunción                    18163 non-null int64
Descripción del sitio donde ocurrio la defunción    18163 non-null object
Año de la defunción                                 18163 non-null int64
Mes de la defunción                                 18163 non-null int64
Descripción del mes de la defunción                 18163 non-null object
Día de la defunción                                 18163 non-null int64
Hora de la defunción                                18163 non-null int64
Minutos de la defunción                             18163 non-null int64
Asistencia médica                                   18163 non-null int64
Descripción de la asistencia médica                 18163 non-null object
Causa CIE a cuatro dígitos                          18163 non-null object
Descripción de la causa CIE                         18163 non-null object
Quien certificó                                     18163 non-null int64
Descripción de quien certificó                      18163 non-null object
Entidad de registro                                 18163 non-null int64
Descripción de la entidad de registro               18163 non-null object
Municipio de registro                               18163 non-null int64
Descripción del municipio de registro               18163 non-null object
Año de registro                                     18163 non-null int64
Mes de registro                                     18163 non-null int64
Descripción del mes de registro                     18163 non-null object
Día de registro                                     18163 non-null int64
Año de la certificación                             15466 non-null float64
Mes de la certificación                             18163 non-null int64
Descripción del mes de la certificación             18163 non-null object
Día de la certificación                             15466 non-null float64
Año de la base de datos                             18163 non-null int64
Razón de mortalidad materna                         18163 non-null int64
Descripción de la razón de mortalidad materna       18163 non-null object
dtypes: float64(2), int64(32), object(24)
memory usage: 8.0+ MB

In [27]:
# Step 3: Create a Dataframe to store data types in materna
m_dtypes = pd.DataFrame(materna.dtypes)
m_dtypes.head()

                                        0
Año de nacimiento                   int64
Mes de nacimiento                   int64
Descripción del mes de nacimiento  object
Día de nacimiento                   int64
Genero                              int64

In [28]:
# 3a: Rename 0 column to be 'DataType'
m_dtypes = m_dtypes.rename(columns={0:'DataType'})
m_dtypes.head()

                                  DataType
Año de nacimiento                    int64
Mes de nacimiento                    int64
Descripción del mes de nacimiento   object
Día de nacimiento                    int64
Genero                               int64

In [29]:
# 3a: Analyze Missing Values
m_dtypes['MissingVal'] = materna.isnull().sum()
m_dtypes.head()

                                  DataType  MissingVal
Año de nacimiento                    int64           0
Mes de nacimiento                    int64           0
Descripción del mes de nacimiento   object           0
Día de nacimiento                    int64           0
Genero                               int64           0

In [30]:
# 3c: Identify number of unique values
m_dtypes['NumUnique'] = materna.nunique()
m_dtypes.head()

                                  DataType  MissingVal  NumUnique
Año de nacimiento                    int64           0         83
Mes de nacimiento                    int64           0         13
Descripción del mes de nacimiento   object           0         13
Día de nacimiento                    int64           0         32
Genero                               int64           0          1

In [31]:
# 3d: Identify the count for each variable
m_dtypes['Count']=materna.count()
m_dtypes.head()

                                  DataType  MissingVal  NumUnique  Count
Año de nacimiento                    int64           0         83  18163
Mes de nacimiento                    int64           0         13  18163
Descripción del mes de nacimiento   object           0         13  18163
Día de nacimiento                    int64           0         32  18163
Genero                               int64           0          1  18163

In [32]:
# Step 4: Run descriptive statistics of object datatypes
materna.describe(include=['object'])

,Descripción del mes de nacimiento,Clave de la edad,Descripción del estado conyugal,Descripción de entidad de residencia,Descripción del municipio de residencia,Descripción de la localidad de residencia,Descripción del tamaño de localidad,Descripción de la ocupación habitual,Descripción de la escolaridad,Descripción de la derechohabiencia,...,Descripción del mes de la defunción,Descripción de la asistencia médica,Causa CIE a cuatro dígitos,Descripción de la causa CIE,Descripción de quien certificó,Descripción de la entidad de registro,Descripción del municipio de registro,Descripción del mes de registro,Descripción del mes de la certificación,Descripción de la razón de mortalidad materna
count,18163,18163,18163,18163,18163,18163,18163,17762,18163,18163,...,18163,18163,18163,18163,18163,18163,18163,18163,18163,18163
unique,13,1,9,36,1862,7160,18,22,12,11,...,13,3,272,272,7,32,1393,12,13,2
top,NO ESPECIFICADO,A,CASADO,México,007 IZTAPALAPA,150330001 Ecatepec de Morelos,1 a 999 habitantes,NO OCUPADOS,SECUNDARIA COMPLETA,NINGUNA,...,OCTUBRE,CON ATENCION MEDICA,O150,O150 Eclampsia en el embarazo,OTRO MEDICO,México,015 CUAUHTEMOC,OCTUBRE,NO ESPECIFICADO,Muertes Maternas para la razón de Mortalidad M...
freq,5586,18163,7973,2605,301,286,3846,10818,4390,6700,...,1616,15627,1548,1548,11153,2014,954,1623,2724,16696

In [33]:
# 4a: Run descriptive statistics of numerical datatypes
materna.describe(include=['number'])

,Año de nacimiento,Mes de nacimiento,Día de nacimiento,Genero,Edad cumplida,Estado conyugal,Entidad de residencia,Municipio de residencia,Localidad de residencia,Tamaño de localidad,...,Entidad de registro,Municipio de registro,Año de registro,Mes de registro,Día de registro,Año de la certificación,Mes de la certificación,Día de la certificación,Año de la base de datos,Razón de mortalidad materna
count,18163.000000,18163.000000,18163.000000,18163.0,18163.000000,18163.000000,18163.000000,18163.000000,18163.000000,18163.000000,...,18163.000000,18163.000000,18163.000000,18163.000000,18163.000000,15466.000000,18163.000000,15466.000000,18163.000000,18163.000000
mean,1972.378186,3.900952,10.173650,2.0,29.716622,3.928206,16.281451,58.749876,56.715961,7.855861,...,16.095744,53.225513,2008.960084,6.649562,15.687276,2008.526510,5.606122,15.665266,2008.960084,0.919231
std,124.765192,3.793616,10.157249,0.0,36.003429,1.464599,7.848476,74.563125,420.835539,5.914919,...,7.950259,64.389210,4.580846,3.455209,9.648856,56.114109,3.955472,8.901255,4.580846,0.272487
min,0.000000,0.000000,0.000000,2.0,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,1.000000,2002.000000,1.000000,0.000000,0.000000,0.000000,0.000000,2002.000000,0.000000
25%,1974.000000,0.000000,0.000000,2.0,22.000000,4.000000,10.000000,13.000000,1.000000,2.000000,...,9.000000,14.000000,2005.000000,4.000000,8.000000,2007.000000,2.000000,8.000000,2005.000000,1.000000
50%,1980.000000,3.000000,8.000000,2.0,28.000000,4.000000,15.000000,35.000000,1.000000,7.000000,...,15.000000,35.000000,2009.000000,7.000000,15.000000,2010.000000,6.000000,16.000000,2009.000000,1.000000
75%,1987.000000,7.000000,19.000000,2.0,34.000000,5.000000,21.000000,78.000000,15.000000,14.000000,...,21.000000,72.000000,2013.000000,10.000000,23.000000,2013.000000,9.000000,23.000000,2013.000000,1.000000
max,2003.000000,12.000000,31.000000,2.0,998.000000,9.000000,35.000000,570.000000,9999.000000,17.000000,...,32.000000,570.000000,2017.000000,12.000000,99.000000,2017.000000,12.000000,99.000000,2017.000000,1.000000

In [34]:
reason_for_death = materna['Descripción de la razón de mortalidad materna']
reason_for_death = np.unique(reason_for_death)
list(reason_for_death)

['Muertes Maternas excluidas para la razón de Mortalidad Materna',
 'Muertes Maternas para la razón de Mortalidad Materna']

In [35]:
last_age = materna['Edad cumplida']
int(last_age.mean())

29

In [36]:
gender = materna['Genero']
int(gender.mean())

2

In [37]:
residence = materna['Descripción de entidad de residencia']
residence = np.unique(residence)
list(residence)

['Aguascalientes',
 'Baja California',
 'Baja California Sur',
 'Campeche',
 'Chiapas',
 'Chihuahua',
 'Coahuila de Zaragoza',
 'Colima',
 'Distrito Federal',
 'Durango',
 'Estados Unidos de Norteamérica',
 'Guanajuato',
 'Guerrero',
 'Hidalgo',
 'Jalisco',
 'Michoacán de Ocampo',
 'Morelos',
 'México',
 'Nayarit',
 'No especificado',
 'Nuevo León',
 'Oaxaca',
 'Otros paises',
 'Otros paises latinoamericanos',
 'Puebla',
 'Querétaro Arteaga',
 'Quintana Roo',
 'San Luis Potosí',
 'Sinaloa',
 'Sonora',
 'Tabasco',
 'Tamaulipas',
 'Tlaxcala',
 'Veracruz de Ignacio de la Llave',
 'Yucatán',
 'Zacatecas']

In [38]:
localsize = materna['Tamaño de localidad']
localsize = np.unique(localsize)
list(localsize)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]

In [39]:
localsize_descrip = materna['Descripción del tamaño de localidad']
localsize_descrip = np.unique(localsize_descrip)
list(localsize_descrip)

['1 a 999            habitantes',
 '1000 a 1999    habitantes',
 '10000 a 14999  habitantes',
 '100000 a 249999 habitantes',
 '1000000 a 1499999  habitantes',
 '15000 a 19999   habitantes',
 '1500000 y más habitantes',
 '2000 a 2499    habitantes',
 '20000 a 29999   habitantes',
 '2500 a 4999    habitantes',
 '250000 a 499999 habitantes',
 '30000 a 39999   habitantes',
 '40000 a 49999   habitantes',
 '5000 a 9999    habitantes',
 '50000 a 74999   habitantes',
 '500000 a 999999  habitantes',
 '75000 a 99999   habitantes',
 'No Especificado.']

In [66]:
local_munci = materna['Descripción del municipio de residencia']
local_munci = np.unique(local_munci)
list(local_munci)

['000 No Especificado',
 '000 No especificado',
 '001 ABASOLO',
 '001 ACACOYAGUA',
 '001 ACAJETE',
 '001 ACAMBAY',
 '001 ACAPONETA',
 '001 ACAPULCO DE JUAREZ',
 '001 ACATIC',
 '001 ACATLAN',
 '001 ACUITZIO',
 '001 AGUASCALIENTES',
 '001 AHOME',
 '001 AHUALULCO',
 '001 AHUMADA',
 '001 AMACUZAC',
 '001 AMAXAC DE GUERRERO',
 '001 AMEALCO DE BONFIL',
 '001 APOZOL',
 '001 ARMERIA',
 '001 BALANCAN',
 '001 CALKINI',
 '001 CANATLAN',
 '001 COMONDU',
 '001 COZUMEL',
 '001 ENSENADA',
 '002 ACALA',
 '002 ACAMBARO',
 '002 ACANCEH',
 '002 ACATENO',
 '002 ACATLAN DE JUAREZ',
 '002 ACATLAN DE PEREZ FIGUEROA',
 '002 ACAXOCHITLAN',
 '002 ACOLMAN',
 '002 ACUÑA',
 '002 AGUA PRIETA',
 '002 AGUALEGUAS',
 '002 AGUILILLA',
 '002 AHUACATLAN',
 '002 AHUACUOTZINGO',
 '002 ALDAMA',
 '002 ANGOSTURA',
 '002 APETATITLAN DE ANTONIO CARVAJAL',
 '002 ASIENTOS',
 '002 ATLATLAHUCAN',
 '002 AZCAPOTZALCO',
 '002 CAMPECHE',
 '002 CANELAS',
 '002 CARDENAS',
 '002 COLIMA',
 '002 FELIPE CARRILLO PUERTO',
 '002 MEXICALI',
 '002 MULEGE',
 '002 PINAL DE AMOLES',
 '003 ACAPETAHUA',
 '003 ACATLAN',
 '003 ACAYUCAN',
 '003 ACTOPAN',
 '003 ACULCO',
 '003 AHUALULCO DE MERCADO',
 '003 AJUCHITLAN DEL PROGRESO',
 '003 AKIL',
 '003 ALAMOS',
 '003 ALLENDE',
 '003 ALTAMIRA',
 '003 ALVARO OBREGON',
 '003 AMATLAN DE CAÑAS',
 '003 AQUISMON',
 '003 ATLANGATEPEC',
 '003 ATOLINGA',
 '003 AXOCHIAPAN',
 '003 BADIRAGUATO',
 '003 CALVILLO',
 '003 CARMEN',
 '003 CENTLA',
 '003 COMALA',
 '003 COYOACAN',
 '003 ISLA MUJERES',
 '003 LA PAZ',
 '003 TECATE',
 '004 ACATZINGO',
 '004 ACTOPAN',
 '004 AGUA BLANCA DE ITURBIDE',
 '004 ALCOZAUCA DE GUERRERO',
 '004 ALLENDE',
 '004 ALMOLOYA DE ALQUISIRAS',
 '004 ALTAMIRANO',
 '004 ALTAR',
 '004 ALTZAYANCA',
 '004 AMACUECA',
 '004 ANGAMACUTIRO',
 '004 APASEO EL ALTO',
 '004 AQUILES SERDAN',
 '004 ARTEAGA',
 '004 AYALA',
 '004 BENITO JUAREZ',
 '004 CADEREYTA DE MONTES',
 '004 CENTRO',
 '004 CHAMPOTON',
 '004 COMPOSTELA',
 '004 CONCORDIA',
 '004 COQUIMATLAN',
 '004 COSIO',
 '004 CUAJIMALPA DE MORELOS',
 '004 CUENCAME',
 '004 OTHON P. BLANCO',
 '004 TIJUANA',
 '005 ACTEOPAN',
 '005 AJACUBA',
 '005 ALMOLOYA DE JUAREZ',
 '005 AMATAN',
 '005 AMATITAN',
 '005 ANAHUAC',
 '005 ANGANGUEO',
 '005 APASEO EL GRANDE',
 '005 APIZACO',
 '005 ASCENSION',
 '005 ASUNCION IXTALTEPEC',
 '005 BENITO JUAREZ',
 '005 BURGOS',
 '005 CALERA',
 '005 CANDELA',
 '005 CARDENAS',
 '005 COLON',
 '005 COMALCALCO',
 '005 COSALA',
 '005 CUAUHTEMOC',
 '005 DURANGO',
 '005 GUSTAVO A. MADERO',
 '005 HECELCHAKAN',
 '005 HUAJICORI',
 '005 JESUS MARIA',
 '005 PLAYAS DE ROSARITO',
 '006 ACULTZINGO',
 '006 AHUACATLAN',
 '006 ALFAJAYUCAN',
 '006 ALMOLOYA DEL RIO',
 '006 AMATENANGO DE LA FRONTERA',
 '006 AMECA',
 '006 APATZINGAN',
 '006 APAXTLA',
 '006 APODACA',
 '006 ASUNCION NOCHIXTLAN',
 '006 ATARJEA',
 '006 BACHINIVA',
 '006 BUCTZOTZ',
 '006 CALPULALPAN',
 '006 CASTAÑOS',
 '006 CATORCE',
 '006 CORREGIDORA',
 '006 CUAUTLA',
 '006 CULIACAN',
 '006 CUNDUACAN',
 '006 GENERAL SIMON BOLIVAR',
 '006 HOPELCHEN',
 '006 IXTLAN DEL RIO',
 '006 IZTACALCO',
 '006 JOSE MARIA MORELOS',
 '006 PABELLON DE ARTEAGA',
 '007 ALMOLOYA',
 '007 AMANALCO',
 '007 AMATENANGO DEL VALLE',
 '007 ARAMBERRI',
 '007 ARCELIA',
 '007 BALLEZA',
 '007 CACALCHEN',
 '007 CAMARGO',
 '007 CEDRAL',
 '007 CELAYA',
 '007 CHOIX',
 '007 CONCEPCION DEL ORO',
 '007 CUATROCIENEGAS',
 '007 CUERNAVACA',
 '007 EL CARMEN TEQUEXQUITLA',
 '007 EMILIANO ZAPATA',
 '007 EZEQUIEL MONTES',
 '007 GOMEZ PALACIO',
 '007 IZTAPALAPA',
 '007 JALA',
 '007 LAZARO CARDENAS',
 '007 MANZANILLO',
 '007 PALIZADA',
 '007 RINCON DE ROMOS',
 '007 SAN JUANITO DE ESCOBEDO',
 '008 AHUAZOTEPEC',
 '008 ALPATLAHUAC',
 '008 AMATEPEC',
 '008 ANGEL ALBINO CORZO',
 '008 APAN',
 '008 AQUILA',
 '008 ARANDAS',
 '008 ATENANGO DEL RIO',
 '008 BATOPILAS',
 '008 BUSTAMANTE',
 '008 CERRITOS',
 '008 CUAPIAXTLA',
 '008 CUAUHTEMOC',
 '008 ELOTA',
 '008 EMILIANO ZAPATA',
 '008 GUADALUPE VICTORIA',
 '008 HUIMANGUILLO',
 '008 HUIMILPAN',
 '008 LA MAGDALENA CONTRERAS',
 '008 LOS CABOS',
 '008 MANUEL DOBLADO',
 '008 SAN JOSE DE GRACIA',
 '008 SOLIDARIDAD',
 '008 TENABO',
 '008 XALISCO',
 '009 ALTO LUCERO DE GUTIERREZ BARRIOS',
 '009 AMECAMECA',
 '009 ARIO',
 '009 ARRIAGA',
 '009 ATLAMAJALCINGO DEL MONTE',
 '009 AYOTZINTEPEC',
 '009 BOCOYNA',
 '009 CADEREYTA JIMENEZ',
 '009 CANSAHCAB',
 '009 CHALCHIHUITES',
 '009 CIUDAD MADERO',
 '009 COMONFORT',
 '009 CUAXOMULCO',
 '009 DEL NAYAR',
 '009 EL ARENAL',
 '009 ESCARCEGA',
 '009 ESCUINAPA',
 '009 FRANCISCO I. MADERO',
 '009 GUANACEVI',
 '009 HUITZILAC',
 '009 JALAPA',
 '009 JALPAN DE SERRA',
 '009 LORETO',
 '009 MILPA ALTA',
 '009 TECOMAN',
 '009 TULUM',
 '010 AJALPAN',
 '010 ALTOTONGA',
 '010 ALVARO OBREGON',
 '010 APAXCO',
 '010 ARTEAGA',
 '010 ATEMAJAC DE BRIZUELA',
 '010 ATITALAQUIA',
 '010 ATLIXTAC',
 '010 BACALAR',
 '010 BEJUCAL DE OCAMPO',
 '010 BUENAVENTURA',
 '010 CALAKMUL',
 '010 CANTAMAYEC',
 '010 CARMEN',
 '010 CHIAUTEMPAN',
 '010 CIUDAD DEL MAIZ',
 '010 CORONEO',
 '010 EL FUERTE',
 '010 EL LLANO',
 '010 FRESNILLO',
 '010 FRONTERA',
 '010 HIDALGO',
 '010 JALPA DE MENDEZ',
 '010 JANTETELCO',
 '010 LANDA DE MATAMOROS',
 '010 ROSAMORADA',
 '010 VILLA DE ALVAREZ',
 '011 ALVARADO',
 '011 ATENCO',
 '011 ATLAPEXCO',
 '011 ATOYAC DE ALVAREZ',
 '011 BELLA VISTA',
 '011 BRISEÑAS',
 '011 CAMARGO',
 '011 CANDELARIA',
 '011 CELESTUN',
 '011 CIUDAD FERNANDEZ',
 '011 CORTAZAR',
 '011 EL MARQUES',
 '011 GENERAL CEPEDA',
 '011 GUASAVE',
 '011 JIUTEPEC',
 '011 JONUTA',
 '011 MUÑOZ DE DOMINGO ARENAS',
 '011 RUIZ',
 '011 SAN FRANCISCO DE LOS ROMO',
 '011 TLAHUAC',
 '012 ALJOJUCA',
 '012 AMATITLAN',
 '012 ATENGUILLO',
 '012 ATIZAPAN',
 '012 ATOTONILCO EL GRANDE',
 '012 AYUTLA DE LOS LIBRES',
 '012 BACUM',
 '012 BERRIOZABAL',
 '012 BUENAVISTA',
 '012 CANDELARIA LOXICHA',
 '012 CARICHI',
 '012 CENOTILLO',
 '012 CIENEGA DE FLORES',
 '012 CUERAMARO',
 '012 ESPAÑITA',
 '012 GENARO CODINA',
 '012 GONZALEZ',
 '012 GUERRERO',
 '012 JOJUTLA',
 '012 LERDO',
 '012 MACUSPANA',
 '012 MAZATLAN',
 '012 PEDRO ESCOBEDO',
 '012 SAN BLAS',
 '012 TANCANHUITZ',
 '012 TLALPAN',
 '013 ALTEPEXI',
 '013 ATIZAPAN DE ZARAGOZA',
 '013 ATOTONILCO DE TULA',
 '013 ATOTONILCO EL ALTO',
 '013 AZOYU',
 '013 BOCHIL',
 '013 CARACUARO',
 '013 CASAS GRANDES',
 '013 CIUDAD VALLES',
 '013 CONKAL',
 '013 DOCTOR MORA',
 '013 GsEMEZ',
 '013 HUAMANTLA',
 '013 JONACATEPEC',
 '013 MAPIMI',
 '013 MOCORITO',
 '013 NACAJUCA',
 '013 NARANJOS AMATLAN',
 '013 PEÑAMILLER',
 '013 XOCHIMILCO',
 '014 AMATLAN DE LOS REYES',
 '014 AMIXTLAN',
 '014 ATLACOMULCO',
 '014 BENITO JUAREZ',
 '014 CALNALI',
 '014 CIUDAD IXTEPEC',
 '014 COAHUAYANA',
 '014 COXCATLAN',
 '014 CUNCUNUL',
 '014 DOCTOR ARROYO',
 '014 DOLORES HIDALGO',
 '014 EL BOSQUE',
 '014 GENERAL FRANCISCO R. MURGUIA',
 '014 GUERRERO',
 '014 HUEYOTLIPAN',
 '014 MAZATEPEC',
 '014 MEZQUITAL',
 '014 PARAISO',
 '014 QUERETARO',
 '014 ROSARIO',
 '014 SANTA MARIA DEL ORO',
 '015 AMOZOC',
 '015 ANGEL R. CABADA',
 '015 ATLAUTLA',
 '015 AUTLAN DE NAVARRO',
 '015 BUENAVISTA DE CUELLAR',
 '015 CACAHOATAN',
 '015 CARDONAL',
 '015 CHARCAS',
 '015 COALCOMAN DE VAZQUEZ PALLARES',
 '015 COATECAS ALTAS',
 '015 CUAUHTEMOC',
 '015 GUANAJUATO',
 '015 GUSTAVO DIAZ ORDAZ',
 '015 IXTACUIXTLA DE MARIANO MATAMOROS',
 '015 MIACATLAN',
 '015 NAZAS',
 '015 SALVADOR ALVARADO',
 '015 SAN JOAQUIN',
 '015 SANTIAGO IXCUINTLA',
 '015 TACOTALPA',
 '016 AQUIXTLA',
 '016 AXAPUSCO',
 '016 AYOTLAN',
 '016 BENJAMIN HILL',
 '016 CATAZAJA',
 '016 CHACSINKIN',
 '016 COAHUAYUTLA DE JOSE MARIA IZAZAGA',
 '016 COENEO',
 '016 COICOYAN DE LAS FLORES',
 '016 CUAUTEPEC DE HINOJOSA',
 '016 DOCTOR GONZALEZ',
 '016 EBANO',
 '016 GENERAL PANFILO NATERA',
 '016 HUANIMARO',
 '016 LA ANTIGUA',
 '016 MIGUEL HIDALGO',
 '016 NOMBRE DE DIOS',
 '016 OCUITUCO',
 '016 SAN IGNACIO',
 '016 SAN JUAN DEL RIO',
 '016 TEAPA',
 '016 TECUALA',
 '017 APAZAPAN',
 '017 ATEMPAN',
 '017 AYAPANGO',
 '017 AYUTLA',
 '017 CABORCA',
 '017 CHAPANTONGO',
 '017 CINTALAPA',
 '017 COCULA',
 '017 CONTEPEC',
 '017 CUAUHTEMOC',
 '017 GALEANA',
 '017 GUADALCAZAR',
 '017 GUADALUPE',
 '017 IRAPUATO',
 '017 JAUMAVE',
 '017 LA COMPAÑIA',
 '017 MATAMOROS',
 '017 MAZATECOCHCO DE JOSE MARIA MORELOS',
 '017 OCAMPO',
 '017 PUENTE DE IXTLA',
 '017 SINALOA',
 '017 TENOSIQUE',
 '017 TEPIC',
 '017 TEQUISQUIAPAN',
 '017 VENUSTIANO CARRANZA',
 '018 AQUILA',
 '018 ATEXCAL',
 '018 CAJEME',
 '018 CALIMAYA',
 '018 CHAPULHUACAN',
 '018 COAPILLA',
 '018 CONCEPCION BUENAVISTA',
 '018 CONTLA DE JUAN CUAMATZI',
 '018 COPALA',
 '018 COPANDARO',
 '018 EL ORO',
 '018 GARCIA',
 '018 HUANUSCO',
 '018 HUEHUETLAN',
 '018 JARAL DEL PROGRESO',
 '018 JIMENEZ',
 '018 LA BARCA',
 '018 MONCLOVA',
 '018 NAVOLATO',
 '018 TEMIXCO',
 '018 TOLIMAN',
 '018 TUXPAN',
 '019 ASTACINGA',
 '019 ATLIXCO',
 '019 BOLAÑOS',
 '019 CANANEA',
 '019 CAPULHUAC',
 '019 CHEMAX',
 '019 CHIHUAHUA',
 '019 CHILCUAUTLA',
 '019 COMITAN DE DOMINGUEZ',
 '019 COPALILLO',
 '019 COTIJA',
 '019 JALPA',
 '019 JERECUARO',
 '019 LA YESCA',
 '019 LAGUNILLAS',
 '019 LLERA',
 '019 MORELOS',
 '019 SAN PEDRO GARZA GARCIA',
 '019 TEPALCINGO',
 '019 TEPETITLA DE LARDIZABAL',
 '020 ATLAHUILCO',
 '020 ATOYATEMPAN',
 '020 BAHIA DE BANDERAS',
 '020 CABO CORRIENTES',
 '020 CARBO',
 '020 CHICXULUB PUEBLO',
 '020 CHINIPAS',
 '020 COACALCO DE BERRIOZABAL',
 '020 CONSTANCIA DEL ROSARIO',
 '020 COPANATOYAC',
 '020 CUITZEO',
 '020 ELOXOCHITLAN',
 '020 JEREZ',
 '020 LA CONCORDIA',
 '020 LEON',
 '020 MATEHUALA',
 '020 MUZQUIZ',
 '020 PANUCO DE CORONADO',
 '020 TEPOZTLAN',
 '021 ATOYAC',
 '021 ATZALA',
 '021 CASIMIRO CASTILLO',
 '021 CHARAPAN',
 '021 CHICHIMILA',
 '021 COATEPEC HARINAS',
 '021 COPAINALA',
 '021 COSOLAPA',
 '021 COYUCA DE BENITEZ',
 '021 DELICIAS',
 '021 EL MANTE',
 '021 EMILIANO ZAPATA',
 '021 GENERAL ESCOBEDO',
 '021 MEXQUITIC DE CARMONA',
 '021 MOROLEON',
 '021 PEÑON BLANCO',
 '021 TETECALA',
 '022 ACUAMANALA DE MIGUEL HIDALGO',
 '022 ATZACAN',
 '022 ATZITZIHUACAN',
 '022 CHALCHIHUITAN',
 '022 CHARO',
 '022 CHIKINDZONOT',
 '022 CIHUATLAN',
 '022 COCOTITLAN',
 '022 COYUCA DE CATALAN',
 '022 DR. BELISARIO DOMINGUEZ',
 '022 EPAZOYUCAN',
 '022 GENERAL TERAN',
 '022 JUAN ALDAMA',
 '022 MATAMOROS',
 '022 MOCTEZUMA',
 '022 NAVA',
 '022 OCAMPO',
 '022 TETELA DEL VOLCAN',
 '023 ATZALAN',
 '023 ATZITZINTLA',
 '023 CHAMULA',
 '023 CHAVINDA',
 '023 COYOTEPEC',
 '023 CUAJINICUILAPA',
 '023 CUILAPAM DE GUERRERO',
 '023 CUMPAS',
 '023 FRANCISCO I. MADERO',
 '023 JUCHIPILA',
 '023 NATIVITAS',
 '023 OCAMPO',
 '023 PENJAMO',
 '023 PUEBLO NUEVO',
 '023 RAYON',
 '023 TLALNEPANTLA',
 '023 ZAPOTLAN EL GRANDE',
 '024 CHANAL',
 '024 CHERAN',
 '024 COCULA',
 '024 CUALAC',
 '024 CUAUTITLAN',
 '024 CUYAMECALCO VILLA DE ZARAGOZA',
 '024 GENERAL ZARAGOZA',
 '024 HUASCA DE OCAMPO',
 '024 LORETO',
 '024 PANOTLA',
 '024 PARRAS',
 '024 PUEBLO NUEVO',
 '024 RIOVERDE',
 '024 RODEO',
 '024 TLALTETELA',
 '024 TLALTIZAPAN',
 '025 AYAHUALULCO',
 '025 CHAHUITES',
 '025 CHALCO',
 '025 CHAPULTENANGO',
 '025 CHILCHOTA',
 '025 COLOTLAN',
 '025 CUAUTEPEC',
 '025 DZAN',
 '025 EMPALME',
 '025 GENERAL ZUAZUA',
 '025 GOMEZ FARIAS',
 '025 HUAUTLA',
 '025 LUIS MOYA',
 '025 MIGUEL ALEMAN',
 '025 PIEDRAS NEGRAS',
 '025 PURISIMA DEL RINCON',
 '025 SALINAS',
 '025 SAN BERNARDO',
 '025 SAN PABLO DEL MONTE',
 '025 TLAQUILTENANGO',
 '026 BANDERILLA',
 '026 CALPAN',
 '026 CHALCATONGO DE HIDALGO',
 '026 CHAPA DE MOTA',
 '026 CHENALHO',
 '026 CHINICUILA',
 '026 CONCEPCION DE BUENOS AIRES',
 '026 CUETZALA DEL PROGRESO',
 '026 ETCHOJOA',
 '026 GRAN MORELOS',
 '026 GUADALUPE',
 '026 HUAZALINGO',
 '026 MAZAPIL',
 '026 ROMITA',
 '026 SAN ANTONIO',
 '026 SAN DIMAS',
 '026 SANTA CRUZ TLAXCALA',
 '026 TLAYACAPAN',
 '027 BENITO JUAREZ',
 '027 CALTEPEC',
 '027 CHAPULTEPEC',
 '027 CHIAPA DE CORZO',
 '027 CHIQUIHUITLAN DE BENITO JUAREZ',
 '027 CHUCANDIRO',
 '027 CUAUTITLAN DE GARCIA BARRAGAN',
 '027 CUTZAMALA DE PINZON',
 '027 FRONTERAS',
 '027 GUACHOCHI',
 '027 HUEHUETLA',
 '027 NUEVO LAREDO',
 '027 RAMOS ARIZPE',
 '027 SALAMANCA',
 '027 SAN CIRO DE ACOSTA',
 '027 SAN JUAN DE GUADALUPE',
 '027 TENANCINGO',
 '027 TOTOLAPAN',
 '028 BOCA DEL RIO',
 '028 CHIAUTLA',
 '028 CHILAPA DE ALVAREZ',
 '028 DZILAM DE BRAVO',
 '028 GUADALUPE',
 '028 HEROICA CIUDAD DE EJUTLA DE CRESPO',
 '028 HUEJUTLA DE REYES',
 '028 MEZQUITAL DEL ORO',
 '028 SABINAS',
 '028 SALVATIERRA',
 '028 SAN JUAN DEL RIO',
 '028 SAN LUIS POTOSI',
 '028 TEOLOCHOLCO',
 '028 XOCHITEPEC',
 '029 CALCAHUALCO',
 '029 CAXHUACAN',
 '029 CHICOLOAPAN',
 '029 CHILPANCINGO DE LOS BRAVO',
 '029 CHURUMUCO',
 '029 DZILAM GONZALEZ',
 '029 ELOXOCHITLAN DE FLORES MAGON',
 '029 GUADALUPE Y CALVO',
 '029 GUAYMAS',
 '029 HUALAHUISES',
 '029 HUICHAPAN',
 '029 MIGUEL AUZA',
 '029 OCAMPO',
 '029 SAN DIEGO DE LA UNION',
 '029 SAN LUIS DEL CORDERO',
 '029 SAN MARTIN CHALCHICUAUTLA',
 '029 TEPEYANCO',
 '029 YAUTEPEC',
 '030 CAMERINO Z. MENDOZA',
 '030 CHAPALA',
 '030 CHICOMUSELO',
 '030 CHICONCUAC',
 '030 ECUANDUREO',
 '030 EL ESPINAL',
 '030 FLORENCIO VILLARREAL',
 '030 GUAZAPARES',
 '030 HERMOSILLO',
 '030 IXMIQUILPAN',
 '030 PADILLA',
 '030 SALTILLO',
 '030 SAN FELIPE',
 '030 SAN NICOLAS TOLENTINO',
 '030 TERRENATE',
 '030 YECAPIXTLA',
 '031 CARRILLO PUERTO',
 '031 CHILON',
 '031 CHIMALHUACAN',
 '031 EPITACIO HUERTA',
 '031 GENERAL CANUTO A. NERI',
 '031 GUERRERO',
 '031 JUAREZ',
 '031 SAN BUENAVENTURA',
 '031 SAN FRANCISCO DEL RINCON',
 '031 SANTA CATARINA',
 '031 SANTA CLARA',
 '031 TAMAZULAPAM DEL ESPIRITU SANTO',
 '031 TETLA DE LA SOLIDARIDAD',
 '031 ZACATEPEC DE HIDALGO',
 '032 CATEMACO',
 '032 CHIQUILISTLAN',
 '032 DONATO GUERRA',
 '032 ERONGARICUARO',
 '032 ESCUINTLA',
 '032 ESPITA',
 '032 GENERAL HELIODORO CASTILLO',
 '032 HIDALGO DEL PARRAL',
 '032 JALTOCAN',
 '032 MORELOS',
 '032 REYNOSA',
 '032 SAN JOSE ITURBIDE',
 '032 SAN JUAN DE SABINAS',
 '032 SANTA MARIA DEL RIO',
 '032 SANTIAGO PAPASQUIARO',
 '032 TETLATLAHUCA',
 '032 ZACUALPAN DE AMILPAS',
 '033 CAZONES',
 '033 COHUECAN',
 '033 DEGOLLADO',
 '033 ECATEPEC DE MORELOS',
 '033 FRANCISCO LEON',
 '033 GABRIEL ZAMORA',
 '033 HALACHO',
 '033 HUAMUXTITLAN',
 '033 HUATABAMPO',
 '033 LINARES',
 '033 RIO BRAVO',
 '033 SAN LUIS DE LA PAZ',
 '033 SAN PEDRO',
 '033 SANTO DOMINGO',
 '033 SUCHIL',
 '033 TLAXCALA',
 '034 CERRO AZUL',
 '034 CORONANGO',
 '034 ECATZINGO',
 '034 FRONTERA COMALAPA',
 '034 HIDALGO',
 '034 HOCABA',
 '034 HUITZUCO DE LOS FIGUEROA',
 '034 LOLOTLA',
 '034 NOCHISTLAN DE MEJIA',
 '034 SAN VICENTE TANCUAYALAB',
 '034 SANTA CATARINA',
 '034 SIERRA MOJADA',
 '034 TAMAZULA',
 '034 TLAXCO',
 '035 CITLALTEPETL',
 '035 COXCATLAN',
 '035 ENCARNACION DE DIAZ',
 '035 FRONTERA HIDALGO',
 '035 HOCTUN',
 '035 HUEHUETOCA',
 '035 IGUALA DE LA INDEPENDENCIA',
 '035 IMURIS',
 '035 JANOS',
 '035 LA HUACANA',
 '035 NORIA DE ANGELES',
 '035 SAN FERNANDO',
 '035 SANTA CRUZ DE JUVENTINO ROSAS',
 '035 SOLEDAD DE GRACIANO SANCHEZ',
 '035 TEPEHUANES',
 '035 TORREON',
 '036 COACOATZINTLA',
 '036 COYOMEAPAN',
 '036 ETZATLAN',
 '036 HUANDACAREO',
 '036 HUEYPOXTLA',
 '036 IGUALAPA',
 '036 JIMENEZ',
 '036 LA GRANDEZA',
 '036 MAGDALENA',
 '036 MIER Y NORIEGA',
 '036 OJOCALIENTE',
 '036 SAN AGUSTIN METZQUITITLAN',
 '036 SANTIAGO MARAVATIO',
 '036 TAMASOPO',
 '036 TLAHUALILO',
 '036 TOTOLAC',
 '036 VIESCA',
 '037 COAHUITLAN',
 '037 EL GRULLO',
 '037 HUEHUETAN',
 '037 HUHI',
 '037 HUIXQUILUCAN',
 '037 IXCATEOPAN DE CUAUHTEMOC',
 '037 JUAREZ',
 '037 METZTITLAN',
 '037 PANUCO',
 '037 SILAO',
 '037 SOTO LA MARINA',
 '037 TAMAZUNCHALE',
 '037 TOPIA',
 '037 ZITLALTEPEC DE TRINIDAD SANCHEZ SANTOS',
 '038 COATEPEC',
 '038 CUAPIAXTLA DE MADERO',
 '038 HUETAMO',
 '038 HUIXTAN',
 '038 HUNUCMA',
 '038 ISIDRO FABELA',
 '038 JOSE AZUETA',
 '038 JULIMES',
 '038 MINERAL DEL CHICO',
 '038 MONTEMORELOS',
 '038 PINOS',
 '038 TAMPACAN',
 '038 TAMPICO',
 '038 TARANDACUAO',
 '038 TZOMPANTEPEC',
 '038 ZARAGOZA',
 '039 COATZACOALCOS',
 '039 CUAUTEMPAN',
 '039 GUADALAJARA',
 '039 HEROICA CIUDAD DE HUAJUAPAN DE LEON',
 '039 HUITIUPAN',
 '039 IXTAPALUCA',
 '039 JUAN R. ESCUDERO',
 '039 MINERAL DEL MONTE',
 '039 MONTERREY',
 '039 NACO',
 '039 NUEVO IDEAL',
 '039 RIO GRANDE',
 '039 TAMPAMOLON CORONA',
 '039 TARIMORO',
 '039 TULA',
 '039 XALOZTOC',
 '040 COATZINTLA',
 '040 CUAUTINCHAN',
 '040 HOSTOTIPAQUILLO',
 '040 HUAUTEPEC',
 '040 HUIXTLA',
 '040 INDAPARAPEO',
 '040 IXTAPAN DE LA SAL',
 '040 IZAMAL',
 '040 LEONARDO BRAVO',
 '040 MADERA',
 '040 SAIN ALTO',
 '040 TAMUIN',
 '040 TIERRA BLANCA',
 '040 VALLE HERMOSO',
 '041 COETZALA',
 '041 CUAUTLANCINGO',
 '041 EL SALVADOR',
 '041 HUAUTLA DE JIMENEZ',
 '041 HUEJUCAR',
 '041 IRIMBO',
 '041 IXTAPAN DEL ORO',
 '041 KANASIN',
 '041 LA INDEPENDENCIA',
 '041 MALINALTEPEC',
 '041 MIXQUIAHUALA DE JUAREZ',
 '041 NACOZARI DE GARCIA',
 '041 PAPALOTLA DE XICOHTENCATL',
 '041 PESQUERIA',
 '041 TANLAJAS',
 '041 URIANGATO',
 '041 VICTORIA',
 '042 COLIPA',
 '042 CUAYUCA DE ANDRADE',
 '042 IXTLAHUACA',
 '042 IXTLAN',
 '042 IXTLAN DE JUAREZ',
 '042 KANTUNIL',
 '042 MARTIR DE CUILAPAN',
 '042 MOLANGO DE ESCAMILLA',
 '042 NAVOJOA',
 '042 SOMBRERETE',
 '042 TANQUIAN DE ESCOBEDO',
 '042 VALLE DE SANTIAGO',
 '042 XICOHTZINCO',
 '043 COMAPA',
 '043 CUETZALAN DEL PROGRESO',
 '043 IXTACOMITAN',
 '043 JACONA',
 '043 JUCHITAN DE ZARAGOZA',
 '043 KAUA',
 '043 LA HUERTA',
 '043 MATACHI',
 '043 METLATONOC',
 '043 NICOLAS FLORES',
 '043 NOGALES',
 '043 TIERRA NUEVA',
 '043 VICTORIA',
 '043 XALATLACO',
 '043 XICOTENCATL',
 '043 YAUHQUEMECAN',
 '044 CORDOBA',
 '044 CUYOACO',
 '044 IXTAPA',
 '044 IXTLAHUACAN DE LOS MEMBRILLOS',
 '044 JALTENCO',
 '044 JIMENEZ',
 '044 KINCHIL',
 '044 LOMA BONITA',
 '044 MOCHITLAN',
 '044 NOPALA DE VILLAGRAN',
 '044 SABINAS HIDALGO',
 '044 TABASCO',
 '044 VANEGAS',
 '044 VILLAGRAN',
 '044 ZACATELCO',
 '045 BENITO JUAREZ',
 '045 CHALCHICOMULA DE SESMA',
 '045 COSAMALOAPAN DE CARPIO',
 '045 IXTAPANGAJOYA',
 '045 IXTLAHUACAN DEL RIO',
 '045 JILOTEPEC',
 '045 JIQUILPAN',
 '045 MEOQUI',
 '045 OLINALA',
 '045 SALINAS VICTORIA',
 '045 TEPECHITLAN',
 '045 VENADO',
 '045 XICHU',
 '046 COSAUTLAN DE CARVAJAL',
 '046 JALOSTOTITLAN',
 '046 JILOTZINGO',
 '046 JIQUIPILAS',
 '046 MAMA',
 '046 MORELOS',
 '046 OMETEPEC',
 '046 OQUITOA',
 '046 SAN FELIPE ORIZATLAN',
 '046 SAN NICOLAS DE LOS GARZA',
 '046 TEPETONGO',
 '046 VILLA DE ARRIAGA',
 '046 YURIRIA',
 '047 CHIAUTLA',
 '047 COSCOMATEPEC',
 '047 JAMAY',
 '047 JIQUIPILCO',
 '047 JITOTOL',
 '047 JUNGAPEO',
 '047 MANI',
 '047 MORIS',
 '047 PEDRO ASCENCIO ALQUISIRAS',
 '047 PITIQUITO',
 '047 VILLA DE GUADALUPE',
 '048 CHIAUTZINGO',
 '048 COSOLEACAQUE',
 '048 JESUS MARIA',
 '048 JOCOTITLAN',
 '048 JUAREZ',
 '048 LA MAGDALENA TLALTELULCO',
 '048 LAGUNILLAS',
 '048 MAGDALENA MIXTEPEC',
 '048 MAXCANU',
 '048 NAMIQUIPA',
 '048 PACHUCA DE SOTO',
 '048 PETATLAN',
 '048 PUERTO PEÑASCO',
 '048 SANTA CATARINA',
 '048 TLALTENANGO DE SANCHEZ ROMAN',
 '049 CHICONCUAUTLA',
 '049 COTAXTLA',
 '049 JOQUICINGO',
 '049 LARRAINZAR',
 '049 MADERO',
 '049 MAYAPAN',
 '049 NONOAVA',
 '049 PILCAYA',
 '049 PISAFLORES',
 '049 QUIRIEGO',
 '049 SANTIAGO',
 '049 VALPARAISO',
 '049 VILLA DE RAMOS',
 '050 CHICHIQUILA',
 '050 COXQUIHUI',
 '050 JOCOTEPEC',
 '050 JUCHITEPEC',
 '050 LA LIBERTAD',
 '050 MAGDALENA PEÑASCO',
 '050 MARAVATIO',
 '050 MERIDA',
 '050 NUEVO CASAS GRANDES',
 '050 PROGRESO DE OBREGON',
 '050 PUNGARABATO',
 '050 SAN FRANCISCO TETLANOHCAN',
 '050 VALLECILLO',
 '050 VETAGRANDE',
 '050 VILLA DE REYES',
 '051 CHIETLA',
 '051 COYUTLA',
 '051 LERMA',
 '051 MAGDALENA TEITIPAC',
 '051 MAPASTEPEC',
 '051 MARCOS CASTELLANOS',
 '051 MINERAL DE LA REFORMA',
 '051 OCAMPO',
 '051 QUECHULTENANGO',
 '051 ROSARIO',
 '051 VILLA DE COS',
 '051 VILLA HIDALGO',
 '052 CUICHAPA',
 '052 JUCHITLAN',
 '052 LAS MARGARITAS',
 '052 LAZARO CARDENAS',
 '052 MAGDALENA TEQUISISTLAN',
 '052 MALINALCO',
 '052 MOTUL',
 '052 OJINAGA',
 '052 SAHUARIPA',
 '052 SAN AGUSTIN TLAXIACA',
 '052 SAN JOSE TEACALCO',
 '052 SAN LUIS ACATLAN',
 '052 VILLA GARCIA',
 '052 VILLA JUAREZ',
 '053 AXTLA DE TERRAZAS',
 '053 CHIGNAHUAPAN',
 '053 CUITLAHUAC',
 '053 LAGOS DE MORENO',
 '053 MAZAPA DE MADERO',
 '053 MELCHOR OCAMPO',
 '053 MORELIA',
 '053 MUNA',
 '053 PRAXEDIS G. GUERRERO',
 '053 SAN BARTOLO TUTOTEPEC',

In [41]:
local_df = materna[['Descripción de entidad de residencia','Tamaño de localidad','Descripción del tamaño de localidad']]
local_df = local_df.sort_values('Tamaño de localidad', axis=0, ascending=True)
len(local_df)

18163

In [42]:
tlx = materna[materna['Descripción de entidad de residencia'] == 'Tlaxcala']
tlx = tlx['Edad cumplida'] 
tlx.head()

0     29
1     36
57    28
65    30
67    29
Name: Edad cumplida, dtype: int64

In [43]:
materna['Descripción del municipio de residencia'].head()

0       013 HUAMANTLA
1       013 HUAMANTLA
2    037 HUIXQUILUCAN
3         001 ACAMBAY
4         056 MORELOS
Name: Descripción del municipio de residencia, dtype: object

In [47]:
materna['Descripción de la localidad de residencia'].head()

0               290130001 Huamantla
1               290130001 Huamantla
2                150370089 El Hielo
3          150010064 Doxteje Centro
4    150560007 San Marcos Tlazalpan
Name: Descripción de la localidad de residencia, dtype: object

In [69]:
materna_region_df = materna[['Descripción del municipio de residencia','Descripción de entidad de residencia']]
materna_region_df.columns = ['Metro Area1', 'City1']
print(materna_region_df.head())

# Store materna_metro as a global variable that can be uploaded to other Jupyter Notebooks
%store materna_region_df

        Metro Area1     City1
0     013 HUAMANTLA  Tlaxcala
1     013 HUAMANTLA  Tlaxcala
2  037 HUIXQUILUCAN    México
3       001 ACAMBAY    México
4       056 MORELOS    México
Stored 'materna_region_df' (DataFrame)

In [45]:
materna['Descripción del tamaño de localidad'].head()

0    40000 a 49999   habitantes
1    40000 a 49999   habitantes
2     1000 a 1999    habitantes
3     1000 a 1999    habitantes
4     2000 a 2499    habitantes
Name: Descripción del tamaño de localidad, dtype: object

In [46]:
materna['Municipio de residencia'].head()

0    13
1    13
2    37
3     1
4    56
Name: Municipio de residencia, dtype: int64